import Head from "next/head";
import AboutMe from "src/components/AboutMe";
import Hero from "src/components/Hero";
import MySkills from "src/components/MySkills/";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import Skill from "@models/Skill";
import { dbConnect } from "@lib/dbConnect";

export default function Home({ skills }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Hero />
        <AboutMe />
        <MySkills skills={skills} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await dbConnect();
    const res = await Skill.find({});

    const skills = res.map((item) => {
      const skill = item.toObject();
      skill._id = `${skill._id}`;
      return skill;
    });

    return { props: { skills } };
  } catch (error) {
    console.log(error);
  }
}


